# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'spring-docker'
    scannerMode: 'Other'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-sambitc'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    repository: 'sambitc/hello-docker-az'
    tags: 'azure'

- task: CopyFiles@2
  inputs:
    SourceFolder: '**/'
    Contents: |
      app.yaml
      service.yaml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'




- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'k8-service-conn'
    namespace: 'default'
    manifests: |
      $(Build.ArtifactStagingDirectory)/app.yaml
      $(Build.ArtifactStagingDirectory)/service.yaml